- name: "Check for Helm installation"
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      if [ ! -x /usr/local/bin/helm ]; then
          echo "NEED_INSTALL"
      else
          helm_version=$(helm version --short | cut -f1 -d"+")
          if [ "$helm_version" != {{ helm_version | quote }} ]; then
              echo "NEED_INSTALL"
          fi
      fi
  register: helm_check
  failed_when: false
  changed_when: false

- name: "Download, extract, and install Helm"
  when: '(helm_check.stdout | trim) == "NEED_INSTALL"'
  block:

    - name: "Create a unique temporary directory for the Helm download"
      when: 'install_helm and my_k3s_node_role == "server"'
      ansible.builtin.tempfile:
        state: directory
        prefix: "helm_dl_"
      register: helm_download_tempdir
      changed_when: false

    - name: "Download and install Helm; remove the temporary directory"
      when: 'install_helm and my_k3s_node_role == "server"'
      block:

        - name: "Download the Helm tarball"
          ansible.builtin.get_url:
            url: "{{ helm_download_url }}"
            dest: '{{ helm_download_tempdir.path }}/{{ helm_download_filename }}'
          register: download_result
          changed_when: false

        - name: "Extract the Helm tarball"
          ansible.builtin.unarchive:
            src: '{{ helm_download_tempdir.path }}/{{ helm_download_filename }}'
            dest: '{{ helm_download_tempdir.path }}'
            remote_src: yes
          register: extract_result
          changed_when: false

        - name: "Move the helm executable into place"
          become: true
          ansible.builtin.shell:
            cmd: |
              set -euo pipefail

              mv -f {{ (helm_download_tempdir.path + "/linux-" + helm_arch + "/helm") | quote }} /usr/local/bin/helm
          args:
            executable: /bin/bash

      always:
        - name: "Remove the temporary directory for the Helm download"
          ansible.builtin.file:
            path: "{{ helm_download_tempdir.path }}"
            state: absent
          changed_when: false