helm_arch: '{{ "arm64" if ansible_facts["architecture"] == "aarch64" else "amd64" }}'
helm_download_filename: "helm-{{ helm_version }}-linux-{{ helm_arch }}.tar.gz"
helm_download_url: "https://get.helm.sh/{{ helm_download_filename }}"
