- name: "Install or upgrade {{ helm_release_name }} via its Helm chart"
  run_once: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      var_args=()
      {% for arg in helm_args %}
      var_args+=({{ arg | quote }})
      {% endfor %}

      set +e
      # Determine whether the Helm repository needs to be added; if so, add it.
      echo "Determining whether the "{{ helm_repo_name | quote }}" helm repository needs to be added"
      if ! helm repo list | grep -q {{ ('^' + helm_repo_name + '\s') | quote }}; then
          echo "Adding the helm repository {{ helm_repo_name | quote }}"
          helm repo add {{ helm_repo_name | quote }} {{ helm_chart_url | quote }} || true
      fi
      # Determine whether the release is already installed.
      echo "Determining whether the "{{ helm_release_name | quote }}" release is already installed"
      helm --namespace {{ helm_namespace | quote }} status {{ helm_release_name | quote }} >/dev/null 2>&1
      helm_status_retval="$?"
      set -e

      # If the release is not installed, install it and exit with a special code to indicate a change.
      if [ "$helm_status_retval" -ne 0 ]; then
          echo "Installing "{{ helm_release_name | quote }}" via the Helm chart"
          helm repo update
          helm install {{ helm_release_name | quote }} {{ (helm_repo_name + '/' + helm_chart_name) | quote }} \
              --namespace {{ helm_namespace | quote }} \
              --version {{ helm_chart_version | quote }} \
              "${var_args[@]}"
          exit 99
      fi

      set +e
      echo "Determining whether a helm upgrade for the "{{ helm_release_name | quote }}" release would result in any changes"
      helm template {{ helm_release_name | quote }} {{ (helm_repo_name + '/' + helm_chart_name) | quote }} \
        --namespace {{ helm_namespace | quote }} \
        --version {{ helm_chart_version | quote }} \
        "${var_args[@]}" | \
            kubectl diff -f -
      helm_template_kubectl_diff_retval="$?"
      if [ "$helm_template_kubectl_diff_retval" -ne 0 ] && [ "$helm_template_kubectl_diff_retval" -ne 1 ]; then
          echo "Error occurred during helm template and kubectl diff" >&2
          exit "$helm_template_kubectl_diff_retval"
      fi
      set -e

      if [ "$helm_template_kubectl_diff_retval" -ne 0 ]; then
          echo "Upgrading "{{ helm_release_name | quote }}" via the Helm chart"
          helm repo update
          helm upgrade {{ helm_release_name | quote }} {{ (helm_repo_name + '/' + helm_chart_name) | quote }} \
              --namespace {{ helm_namespace | quote }} \
              --version {{ helm_chart_version | quote }} \
              "${var_args[@]}"
          exit 99
      fi
  args:
    executable: /bin/bash
  register: helm_chart_install_or_upgrade_result
  changed_when: 'helm_chart_install_or_upgrade_result.rc == 99'
  failed_when: 'helm_chart_install_or_upgrade_result.rc not in [0, 99]'
