- name: "Install or upgrade {{ helm_release_name }} via its Helm chart"
  run_once: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      var_args=()
      {% for arg in helm_args %}
      var_args+=({{ arg | quote }})
      {% endfor %}

      {% if not helm_chart_url.startswith('oci://') %}
      set +e
      # Determine whether the Helm repository needs to be added; if so, add it.
      printf "Determining whether the %s helm repository needs to be added\n" {{ helm_repo_name | quote }}
      if ! helm repo list | grep -q {{ ('^' + helm_repo_name + '\s') | quote }}; then
          printf "Adding the helm repository: %s\n" {{ helm_repo_name | quote }}
          helm repo add {{ helm_repo_name | quote }} {{ helm_chart_url | quote }} || true
      fi
      set -e

      echo "Updating Helm repositories."
      helm repo update
      {% endif %}

      set +e
      # Determine whether the release is already installed.
      printf "Determining whether the %s release is already installed\n" {{ helm_release_name | quote }}
      helm --namespace {{ helm_namespace | quote }} status {{ helm_release_name | quote }} >/dev/null 2>&1
      helm_status_retval="$?"
      set -e

      # If the release is not installed, install it and exit with a special code to indicate a change.
      if [ "$helm_status_retval" -ne 0 ]; then
          printf "Installing the %s release via the Helm chart\n" {{ helm_release_name | quote }}
          helm install {{ helm_release_name | quote }} {{ helm_chart_ref | quote }} \
              --namespace {{ helm_namespace | quote }} \
              --version {{ helm_chart_version | quote }} \
              "${var_args[@]}"
          exit 99
      fi

      set +e
      printf "Determining the installed Helm chart version of the %s release\n" {{ helm_release_name | quote }}
      installed_helm_chart_version=$(helm -n {{ helm_namespace | quote }} list --selector name={{ helm_release_name | quote }} -o json | jq -r '.[] | .chart' | sed -e 's/^'{{ helm_chart_name | quote }}'-//g')
      echo "Installed Helm chart version: ${installed_helm_chart_version}"
      set -e

      set +e
      printf "Determining whether a helm upgrade for the %s release would result in any changes\n" {{ helm_release_name | quote }}
      helm template {{ helm_release_name | quote }} {{ helm_chart_ref | quote }} \
        --namespace {{ helm_namespace | quote }} \
        --version {{ helm_chart_version | quote }} \
        "${var_args[@]}" \
      {% if (helm_diff_yq_filter_expressions | length) > 0 %}
      {% for helm_diff_exclude_yq_expression in helm_diff_yq_filter_expressions %}
            | yq {{ helm_diff_exclude_yq_expression | quote }} - --yaml-output \
      {% endfor %}
            | sed -e 's/^--- null$//g' \
      {% endif %}
            | kubectl diff -f - 2>&1
      helm_template_kubectl_diff_retval="$?"
      if [ "$helm_template_kubectl_diff_retval" -ne 0 ] && [ "$helm_template_kubectl_diff_retval" -ne 1 ]; then
          echo "Error occurred during helm template and kubectl diff" >&2
          exit "$helm_template_kubectl_diff_retval"
      fi
      set -e

      if [ "$installed_helm_chart_version" != {{ helm_chart_version | quote }} ] ||[ "$helm_template_kubectl_diff_retval" -ne 0 ]; then
          printf "Upgrading the %s release via the Helm chart\n" {{ helm_release_name | quote }}
          helm upgrade {{ helm_release_name | quote }} {{ helm_chart_ref | quote }} \
              --namespace {{ helm_namespace | quote }} \
              --version {{ helm_chart_version | quote }} \
              "${var_args[@]}"
          exit 99
      else
          printf "Helm release %s is already up-to-date\n" {{ helm_release_name | quote }}
      fi
  args:
    executable: /bin/bash
  vars:
    helm_chart_ref: '{{ (helm_chart_url if helm_chart_url.startswith("oci://") else (helm_repo_name + "/" + helm_chart_name)) }}'
  register: helm_chart_install_or_upgrade_result
  changed_when: 'helm_chart_install_or_upgrade_result.rc == 99'
  failed_when: 'helm_chart_install_or_upgrade_result.rc not in [0, 99]'
