k3s_hosts_group: "all_hosts"
k3s_version: "v1.37.0+k3s1"
k3s_cluster_pod_network_cidr: "10.100.0.0/16"
k3s_enable_wireguard_network_encryption: true
k3s_storage_dir: ""

create_k3s_user: true
k3s_user: k3s
k3s_user_home: "/home/{{ k3s_user }}"
k3s_user_id: 2121

k3s_group: k3s
k3s_group_id: 2121

num_k3s_server_nodes: '{{ 3 if (groups[k3s_hosts_group] | length) >= 3 else 1 }}'

install_cni_plugins: false
cni_plugins_version: "v1.9.1"

install_multus_cni: false
multus_cni_version: "v4.3.1"
multus_cni_protocol_version: "1.0.0"

install_helm: true
helm_version: "v4.3.0"

install_headlamp: true
headlamp_helm_chart_version: "0.45.0"
headlamp_helm_base_args:
  - --set
  - serviceAccount.create=true
  - --set
  - serviceAccount.name=headlamp-admin
  - --set
  - clusterRole.create=true
  - --set
  - clusterRole.name=cluster-admin
headlamp_ingress_enabled: true
headlamp_ingress_path: "/headlamp"
headlamp_ingress_path_type: "Prefix"
headlamp_ingress_middlewares:
  - "kube-system-add-trailing-slash-headlamp@kubernetescrd"
headlamp_ingress_extra_annotations: {}
headlamp_ingress_annotations_combined: |
  {{
      { "traefik.ingress.kubernetes.io/router.middlewares": (headlamp_ingress_middlewares | join(",")) }
      | combine(headlamp_ingress_extra_annotations)
  }}
headlamp_helm_ingress_args: |
  [
    "--set",
    "config.baseURL=" + (headlamp_ingress_path | quote),
    "--set",
    "ingress.enabled=true" if headlamp_ingress_enabled else "ingress.enabled=false",
  ] +
  (
    [
      "--set",
      "ingress.hosts[0].paths[0].path=" + (headlamp_ingress_path | quote),
      "--set",
      "ingress.hosts[0].paths[0].type=" + (headlamp_ingress_path_type | quote),
      "--set-json",
      "ingress.annotations=" + (headlamp_ingress_annotations_combined | to_json | quote),
    ] if headlamp_ingress_enabled else []
  )
headlamp_helm_extra_args: []

install_longhorn: true
longhorn_helm_chart_version: "1.13.0"
longhorn_helm_extra_args: []
longhorn_default_volume_replica_count: '{{ 3 if (groups[k3s_hosts_group] | length) >= 5 else 2 if (groups[k3s_hosts_group] | length) >= 3 else 1 }}'
longhorn_ingress_enabled: true
longhorn_ingress_path: "/longhorn"
longhorn_ingress_path_type: "Prefix"
longhorn_ingress_middlewares:
  - "longhorn-system-basic-auth-longhorn-ui@kubernetescrd"
  - "longhorn-system-add-trailing-slash-longhorn-ui@kubernetescrd"
  - "longhorn-system-strip-prefix-longhorn-ui@kubernetescrd"
longhorn_ingress_extra_annotations: {}
longhorn_ui_credentials:
  - username: "lhadmin"
    password: "adMiNlH3223"
