- name: "Install required packages for Longhorn"
  become: true
  ansible.builtin.package:
    name:
      - apache2-utils
      # Required for NFS support in Longhorn (ReadWriteMany volumes)
      - '{{ "nfs-common" if ansible_facts.os_family == "Debian" else "nfs-utils" }}'
    state: present
    update_cache: true

- name: "Calculate htpasswd lines for Longhorn"
  ansible.builtin.shell:
    cmd: |
        set -e
        set -o pipefail

        {% for creds in longhorn_ui_credentials %}
        htpasswd -nb {{ creds.username | quote }} {{ creds.password | quote }}
        {% endfor %}
  args:
    executable: /bin/bash
  changed_when: false
  register: longhorn_htpasswd_result

- name: "Create a temporary directory for the Longhorn ancillary resources manifest"
  run_once: true
  ansible.builtin.tempfile:
    state: directory
    prefix: "longhorn-middleware"
  register: longhorn_middleware_tempdir
  changed_when: false

- name: "Template and apply the Longhorn ancillary resources manifest; remove the temporary directory"
  run_once: true
  block:

    - name: "Template the Longhorn ancillary resources manifest"
      ansible.builtin.template:
        src: "longhorn-namespace-and-related-resources.yaml.j2"
        dest: "{{ longhorn_middleware_tempdir.path }}/longhorn-namespace-and-related-resources.yaml"
        mode: '0644'
      changed_when: false

    - name: "Apply the Longhorn ancillary resources manifest"
      become: true
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail

          set +e
          kubectl diff -f {{ longhorn_middleware_tempdir.path | quote }}/longhorn-namespace-and-related-resources.yaml
          retval="$?"
          set -e

          if [ "$retval" -ne 0 ]; then
              kubectl apply -f {{ longhorn_middleware_tempdir.path | quote }}/longhorn-namespace-and-related-resources.yaml
              exit 99
          fi
      args:
        executable: /bin/bash
      register: longhorn_ingress_middleware_apply_result
      changed_when: "longhorn_ingress_middleware_apply_result.rc == 99"
      failed_when: "longhorn_ingress_middleware_apply_result.rc not in [0, 99]"

  always:
    - name: "Remove the temporary directory for the Longhorn ancillary resources manifest"
      ansible.builtin.file:
        path: "{{ longhorn_middleware_tempdir.path }}"
        state: absent
      changed_when: false

# TODO: Find a way to check whether Longhorn is already installed, and the correct version and configuration, before attempting installation.
- name: "Install Longhorn via the Longhorn Helm chart"
  run_once: true
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      helm repo add longhorn "{{ longhorn_helm_chart_url }}" || true
      helm repo update

      var_args=()
      {% for arg in longhorn_helm_base_args + longhorn_helm_storage_dir_args + longhorn_helm_ingress_args + longhorn_helm_extra_args %}
      var_args+=({{ arg | quote }})
      {% endfor %}

      helm upgrade --install longhorn longhorn/longhorn \
          --namespace longhorn-system \
          --version "{{ longhorn_helm_chart_version }}" \
          "${var_args[@]}"
  args:
    executable: /bin/bash
  changed_when: true
