- name: "Create a temporary directory for the Headlamp ingress middleware manifest"
  run_once: true
  ansible.builtin.tempfile:
    state: directory
    prefix: "headlamp-middleware"
  register: headlamp_middleware_tempdir
  changed_when: false

- name: "Template and apply the Headlamp ingress middleware manifest; remove the temporary directory"
  run_once: true
  block:

    - name: "Template the Headlamp ingress middleware manifest"
      ansible.builtin.template:
        src: "headlamp-ingress-middleware.yaml.j2"
        dest: "{{ headlamp_middleware_tempdir.path }}/headlamp-ingress-middleware.yaml"
      changed_when: false

    - name: "Apply the Headlamp ingress middleware manifest"
      become: true
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail

          set +e
          kubectl diff -f {{ headlamp_middleware_tempdir.path | quote }}/headlamp-ingress-middleware.yaml
          retval="$?"
          set -e

          if [ "$retval" -ne 0 ]; then
              kubectl apply -f {{ headlamp_middleware_tempdir.path | quote }}/headlamp-ingress-middleware.yaml
              exit 99
          fi
      args:
        executable: /bin/bash
      register: headlamp_ingress_middleware_apply_result
      changed_when: "headlamp_ingress_middleware_apply_result.rc == 99"
      failed_when: "headlamp_ingress_middleware_apply_result.rc not in [0, 99]"

  always:
    - name: "Remove the temporary directory for the Headlamp ingress middleware manifest"
      ansible.builtin.file:
        path: "{{ headlamp_middleware_tempdir.path }}"
        state: absent
      changed_when: false

# TODO: Find a way to check whether Headlamp is already installed, and the correct version and configuration, before attempting installation.
- name: "Install Headlamp via the Headlamp Helm chart"
  run_once: true
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      helm repo add headlamp "{{ headlamp_helm_chart_url }}" || true
      helm repo update

      var_args=()
      {% for arg in headlamp_helm_extra_args %}
      var_args+=({{ arg | quote }})
      {% endfor %}

      helm upgrade --install headlamp headlamp/headlamp \
          --namespace kube-system \
          --version "{{ headlamp_helm_chart_version }}" \
          --set serviceAccount.create=true \
          --set serviceAccount.name=headlamp-admin \
          --set clusterRole.create=true \
          --set clusterRole.name=cluster-admin \
          --set config.baseURL={{ headlamp_ingress_path | quote }} \
          --set ingress.enabled={{ "true" if headlamp_ingress_enabled else "false" }} \
      {% if headlamp_ingress_enabled %}
          --set ingress.hosts[0].paths[0].path={{ headlamp_ingress_path | quote }} \
          --set ingress.hosts[0].paths[0].type={{ headlamp_ingress_path_type | quote }} \
          --set-json ingress.annotations={{ headlamp_ingress_annotations | to_json | quote }} \
      {% endif %}
          "${var_args[@]}"
  args:
    executable: /bin/bash
  vars:
    headlamp_ingress_annotations: >-
      {{ { "traefik.ingress.kubernetes.io/router.middlewares": (headlamp_ingress_middlewares | join(",")) } | combine(headlamp_ingress_extra_annotations) }}
