cni_plugins_cni_dir: "/var/lib/rancher/k3s/data/cni"
cni_plugins_arch: '{{ "arm64" if ansible_facts.architecture == "aarch64" else "amd64" }}'
cni_plugins_download_url: 'https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/cni-plugins-linux-{{ cni_plugins_arch }}-{{ cni_plugins_version }}.tgz'
cni_plugins_needed_plugins:
  - ptp
  - vlan
  - host-device
  - tuning
  - dhcp
  - static
  - macvlan
  - dummy
  - ipvlan
