###################################################################################
# GET INFORMATION FOR EACH NODE ABOUT ANY EXISTING K3S INSTALLATION ON THAT NODE. #
###################################################################################

- name: "Determine whether the k3s binary is installed on the host"
  ansible.builtin.stat:
    path: "/usr/local/bin/k3s"
  register: stat_result_k3s_binary

- name: "Determine which version of k3s is installed on the host"
  ansible.builtin.shell:
    cmd: |
        [ -x /usr/local/bin/k3s ] && /usr/local/bin/k3s --version | head -1 | awk '{print $3}' | xargs
  args:
    executable: /bin/bash
  register: result_get_k3s_version
  changed_when: false
  failed_when: false

- name: "Determine whether k3s is installed on the host as server, agent, or neither"
  ansible.builtin.shell:
    cmd: |
        if [ -x /usr/local/bin/k3s-uninstall.sh ]; then
            echo "server"
        elif [ -x /usr/local/bin/k3s-agent-uninstall.sh ]; then
            echo "agent"
        fi
  args:
    executable: /bin/bash
  register: result_get_k3s_role
  changed_when: false
  failed_when: false

- name: "Build a composite fact detailing the status of the k3s installation on the host"
  ansible.builtin.set_fact:
    k3s_installed_info:
      is_installed: '{{ stat_result_k3s_binary.stat.exists and stat_result_k3s_binary.stat.isreg and (result_get_k3s_role.stdout | trim) != "" }}'
      version: '{{ result_get_k3s_version.stdout | trim }}'
      role: '{{ result_get_k3s_role.stdout | trim }}'
      need_install_or_reinstall: |
          {{
              (not (stat_result_k3s_binary.stat.exists and stat_result_k3s_binary.stat.isreg and (result_get_k3s_role.stdout | trim) != ""))
              or (result_get_k3s_version.stdout | trim) != k3s_version
              or (result_get_k3s_role.stdout | trim) != my_k3s_node_role
          }}
