####################################################################################################
# FIND THE FIRST SERVER NODE TO USE AS THE K3S API HOST, AND GET ITS TOKEN.                        #
# THE API HOST MUST BE A DIFFERENT NODE, SINCE IT WILL BE USED TO PERFORM OPERATIONS ON THIS NODE. #
####################################################################################################

- name: "Set the k3s API host, IPV4 address and token for joining this host to the cluster, to empty strings"
  ansible.builtin.set_fact:
    k3s_api_host: ""
    k3s_api_host_ipv4: ""
    k3s_api_host_token: ""

- name: "Set the k3s API host and IPV4 address for joining this host to the cluster, to the first host which is running k3s server, excluding the current host"
  ansible.builtin.set_fact:
    k3s_api_host: "{{ item }}"
    k3s_api_host_ipv4: "{{ hostvars[item].ansible_facts.default_ipv4.address }}"
  when:
    - k3s_api_host == ""
    - item != k3s_install_host
    - 'hostvars[item]["k3s_installed_info"].is_installed'
    - 'hostvars[item]["k3s_installed_info"].role == "server"'
  loop: "{{ groups[k3s_hosts_group] }}"

- name: "Slurp the server token for the k3s API host; set the k3s_api_host_token fact"
  when: 'k3s_api_host != ""'
  block:
    - name: "Slurp the server token for the k3s API host"
      become: true
      ansible.builtin.slurp:
        src: "/var/lib/rancher/k3s/server/token"
      # We have to default this to a non-empty host in order to avoid getting an error about an empty delegate_to value,
      # even though the "when" condition would prevent this task from running in that case.
      delegate_to: "{{ k3s_api_host | default(k3s_install_host, true) }}"
      register: k3s_api_host_token_file_encoded

    - name: "Decode the server token for the k3s API host into the current host"
      ansible.builtin.set_fact:
        k3s_api_host_token: "{{ k3s_api_host_token_file_encoded['content'] | b64decode | trim }}"

- name: "Show the k3s API host and token for joining this host to the cluster"
  ansible.builtin.debug:
    msg: "k3s_api_host: {{ k3s_api_host }}  k3s_api_host_ipv4: {{ k3s_api_host_ipv4 }}  k3s_api_host_token: {{ k3s_api_host_token | regex_replace('.', '*') }}"

#################################################################################
# CORDON, DRAIN AND DELETE THE NODE FROM THE CLUSTER, UNINSTALL K3S, IF NEEDED. #
#################################################################################

- name: "Cordon, drain and delete my node: {{ k3s_install_host }}, executing the commands on {{ k3s_api_host }}"
  when: 'k3s_installed_info.is_installed and k3s_installed_info.need_install_or_reinstall and k3s_api_host != ""'
  # We have to default this to a non-empty host in order to avoid getting an error about an empty delegate_to value,
  # even though the "when" condition would prevent this task from running in that case.
  delegate_to: '{{ k3s_api_host | default(k3s_install_host, true) }}'
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      kubectl cordon {{ k3s_install_host.split('.')[0] }}
      kubectl drain {{ k3s_install_host.split('.')[0] }} --ignore-daemonsets --delete-emptydir-data --force
      kubectl delete node {{ k3s_install_host.split('.')[0] }}
  args:
    executable: /bin/bash

- name: "Uninstall k3s on my node: {{ k3s_install_host }}"
  when: 'k3s_installed_info.is_installed and k3s_installed_info.need_install_or_reinstall'
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      {% if k3s_installed_info.role == "server" %}
      /usr/local/bin/k3s-uninstall.sh
      {% elif k3s_installed_info.role == "agent" %}
      /usr/local/bin/k3s-agent-uninstall.sh
      {% endif %}
  args:
    executable: /bin/bash

##############################################################################
# INSTALL K3S ON THE NODE; JOIN THE CLUSTER IF WE HAVE ANOTHER RUNNING NODE. #
##############################################################################

- name: "If this node is listed in the cluster, delete it"
  when: 'k3s_api_host != ""'
  delegate_to: '{{ k3s_api_host | default(k3s_install_host, true) }}'
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      kubectl delete node {{ k3s_install_host.split('.')[0] | quote }}
  args:
    executable: /bin/bash
  register: result_delete_my_node
  failed_when: false
  changed_when: 'result_delete_my_node.rc == 0'

- name: "Install k3s {{ my_k3s_node_role }} on my node: {{ k3s_install_host }}"
  when: 'k3s_installed_info.need_install_or_reinstall'
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      curl -sfL {{ k3s_installer_script_url | quote }} | \
          INSTALL_K3S_VERSION={{ k3s_version | quote }} \
          INSTALL_K3S_EXEC="{{ install_k3s_exec_args | join(' ') }}" \
      {% if k3s_api_host_ipv4 != "" and k3s_api_host_token != "" %}
          K3S_URL={{ ("https://" + k3s_api_host_ipv4 + ":6443") | quote }} \
          K3S_TOKEN={{ k3s_api_host_token | quote }} \
      {% endif %}
      {% if my_k3s_node_role == "server" %}
          K3S_KUBECONFIG_MODE="640" \
          K3S_KUBECONFIG_GROUP={{ k3s_group | quote }} \
      {% endif %}
          sh -
  args:
    executable: /bin/bash
  vars:
    install_k3s_exec_args: |
      {{
        [
          "server --secrets-encryption --flannel-backend=wireguard-native" if my_k3s_node_role == "server" else "",
          "--cluster-init" if my_k3s_node_role == "server" and k3s_api_host_ipv4 == "" else ""
        ] | reject('==', '') | list
      }}

- name: "Update the composite fact detailing the status of the k3s installation on the host"
  ansible.builtin.set_fact:
    k3s_installed_info:
      is_installed: true
      version: '{{ k3s_version }}'
      role: '{{ my_k3s_node_role }}'
      need_install_or_reinstall: false

- name: "Create a directory for k3s storage, and symlink it into place."
  when: 'k3s_storage_dir != ""'
  become: true
  block:
    - name: "Create the {{ k3s_storage_dir }}/k3s directory"
      ansible.builtin.file:
        path: "{{ k3s_storage_dir }}/k3s"
        state: directory
        mode: '0755'

    - name: "Create the {{ k3s_storage_dir }}/k3s/storage directory"
      ansible.builtin.file:
        path: "{{ k3s_storage_dir }}/k3s/storage"
        state: directory
        mode: '0701'

    - name: "Create a symlink pointing /var/lib/rancher/k3s/storage to {{ k3s_storage_dir }}/k3s/storage"
      ansible.builtin.file:
        src: "{{ k3s_storage_dir }}/k3s/storage"
        dest: "/var/lib/rancher/k3s/storage"
        state: link
        force: true

########################################################################
# CREATE THE $HOME/.kube DIRECTORY FOR THE SUPERUSER AND THE k3s USER. #
# SYMLINK THE KUBECONFIG FILE INTO IT.                                 #
# THIS IS NECESSARY BECAUSE OTHER KUBERNETES UTILITIES DON'T KNOW HOW  #
# TO READ K3S' KUBECONFIG FILE.                                        #
########################################################################

- name: "Create the ~/.kube directory for the superuser"
  when: 'my_k3s_node_role == "server"'
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      mkdir -p "$HOME/.kube"
      chmod 0750 "$HOME/.kube"
      ln -sf /etc/rancher/k3s/k3s.yaml "$HOME/.kube/config"
  args:
    executable: /bin/bash

- name: "Create the ~/.kube directory for the {{ k3s_user }} user, if we created the user"
  when: 'create_k3s_user and my_k3s_node_role == "server"'
  become: true
  become_user: "{{ k3s_user }}"
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      mkdir -p "$HOME/.kube"
      chmod 0750 "$HOME/.kube"
      ln -sf /etc/rancher/k3s/k3s.yaml "$HOME/.kube/config"
  args:
    executable: /bin/bash
