###################################################################################
# GET INFORMATION FOR EACH NODE ABOUT ANY EXISTING K3S INSTALLATION ON THAT NODE. #
###################################################################################

- name: "Determine whether the k3s binary is installed on the host"
  ansible.builtin.stat:
    path: "/usr/local/bin/k3s"
  register: k3s_cluster_stat_result_k3s_binary

- name: "Determine which version of k3s is installed on the host"
  ansible.builtin.shell:
    cmd: |
        set -euo pipefail

        [ -x /usr/local/bin/k3s ] && /usr/local/bin/k3s --version | head -1 | awk '{print $3}' | xargs
  args:
    executable: /bin/bash
  register: k3s_cluster_result_get_k3s_version
  changed_when: false
  failed_when: false

- name: "Determine whether k3s is installed on the host as server, agent, or neither"
  ansible.builtin.shell:
    cmd: |
        if [ -d /var/lib/rancher/k3s/server ]; then
            echo "server"
        elif [ -d /var/lib/rancher/k3s/agent ]; then
            echo "agent"
        fi
  args:
    executable: /bin/bash
  register: k3s_cluster_result_get_k3s_role
  changed_when: false
  failed_when: false

- name: "Build a composite fact detailing the status of the k3s installation on the host"
  ansible.builtin.set_fact:
    k3s_cluster_k3s_installed_info:
      is_installed: |
        {{
            k3s_cluster_stat_result_k3s_binary.stat.exists
            and k3s_cluster_stat_result_k3s_binary.stat.isreg
            and (k3s_cluster_result_get_k3s_role.stdout | trim) != ""
        }}
      version: '{{ k3s_cluster_result_get_k3s_version.stdout | trim }}'
      role: '{{ k3s_cluster_result_get_k3s_role.stdout | trim }}'
      need_install_or_reinstall: |
          {{
              (not (k3s_cluster_stat_result_k3s_binary.stat.exists
                and k3s_cluster_stat_result_k3s_binary.stat.isreg and (k3s_cluster_result_get_k3s_role.stdout | trim) != ""))
              or (k3s_cluster_result_get_k3s_version.stdout | trim) != k3s_version
              or (k3s_cluster_result_get_k3s_role.stdout | trim) != node_k3s_role
          }}

- name: "Show the k3s installation composite fact before installing or reinstalling k3s"
  ansible.builtin.debug:
    var: k3s_cluster_k3s_installed_info

# TODO: If possible, add an assertion to compare k3s_cluster_k3s_installed_info.version to k3s_version,
#       and fail if they are more than one minor version apart in either direction.
#       If there is ever a version 2.x.y of K3s, we would have to update the assertion logic
#       to accommodate transitioning between the latest allowed 1.x.y version(s) and the
#       earliest 2.x.y versions.

####################################################################################
# INSTALL OR REINSTALL K3S ON EACH NODE AS NEEDED BASED ON THE STATE OF EACH NODE. #
####################################################################################

- name: "Install or reinstall k3s on each node, in order"
  when: inventory_hostname == k3s_install_host and k3s_cluster_k3s_installed_info.need_install_or_reinstall
  ansible.builtin.include_tasks:
    file: "k3s_install_single_node.yml"
  # Intentional: reinstall only hosts in the current play; cluster topology is based on groups[k3s_hosts_group].
  loop: '{{ ansible_play_hosts_all }}'
  loop_control:
    loop_var: k3s_install_host

- name: "Show the k3s installation composite fact after installing or reinstalling k3s"
  ansible.builtin.debug:
    var: k3s_cluster_k3s_installed_info

- name: "Wait for k3s to come up and be accessible"
  when: 'node_k3s_role == "server"'
  block:
    - name: "Wait for the k3s service to start listening on the default port"
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 6443
        state: started
        timeout: 60
      changed_when: false

    - name: "Wait for the k3s service to be fully operational"
      become: true
      ansible.builtin.shell:
        cmd: |
            set -euo pipefail

            kubectl --kubeconfig=/etc/rancher/k3s/k3s.yaml get node
      args:
        executable: /bin/bash
      register: k3s_cluster_result_wait_for_k3s_api
      retries: 10
      delay: 6
      until: k3s_cluster_result_wait_for_k3s_api.rc == 0
      changed_when: false

#######################################################
# DO ANY REQUIRED SETUP FOR THE K3S STORAGE DIRECTORY #
#######################################################

- name: "Create a directory for k3s storage, and symlink it into place."
  when: 'k3s_storage_dir != ""'
  become: true
  block:
    - name: "Create the {{ k3s_storage_dir }}/k3s directory"
      ansible.builtin.file:
        path: "{{ k3s_storage_dir }}/k3s"
        state: directory
        mode: '0755'

    - name: "Create the {{ k3s_storage_dir }}/k3s/storage directory"
      ansible.builtin.file:
        path: "{{ k3s_storage_dir }}/k3s/storage"
        state: directory
        mode: '0701'

    - name: "Create a symlink pointing /var/lib/rancher/k3s/storage to {{ k3s_storage_dir }}/k3s/storage"
      ansible.builtin.file:
        src: "{{ k3s_storage_dir }}/k3s/storage"
        dest: "/var/lib/rancher/k3s/storage"
        state: link
        force: true

########################################################
# FIX THE PERMISSIONS AND GROUP OF THE KUBECONFIG FILE #
#######################################################

- name: "Fix the permissions and group of the /etc/rancher/k3s/k3s.yaml kubeconfig file"
  when: 'node_k3s_role == "server"'
  become: true
  ansible.builtin.file:
    path: '/etc/rancher/k3s/k3s.yaml'
    group: '{{ k3s_group }}'
    state: file
    mode: '0640'

- name: "Make the /etc/rancher/k3s/k3s.yaml kubeconfig file permissions and group permanent"
  when: 'node_k3s_role == "server"'
  become: true
  ansible.builtin.lineinfile:
    path: '/etc/systemd/system/k3s.service.env'
    regexp: '^K3S_KUBECONFIG_MODE='
    line: 'K3S_KUBECONFIG_MODE=0640'

########################################################################
# CREATE THE $HOME/.kube DIRECTORY FOR THE SUPERUSER AND THE k3s USER. #
# SYMLINK THE KUBECONFIG FILE INTO IT.                                 #
# THIS IS NECESSARY BECAUSE OTHER KUBERNETES UTILITIES DON'T KNOW HOW  #
# TO READ K3S' KUBECONFIG FILE.                                        #
########################################################################

- name: "Create the ~/.kube directory for the superuser"
  when: 'node_k3s_role == "server"'
  become: true
  block:
    - name: "Make the superuser's .kube directory"
      ansible.builtin.file:
        path: '{{ superuser_home }}/.kube'
        state: directory
        owner: '{{ superuser_name }}'
        group: '{{ superuser_group }}'
        mode: '0750'

    - name: "Link /etc/rancher/k3s/k3s.yaml to the superuser's .kube/config"
      ansible.builtin.file:
        src: '/etc/rancher/k3s/k3s.yaml'
        path: '{{ superuser_home }}/.kube/config'
        state: link
        force: true

- name: "Create the ~/.kube directory for the {{ k3s_user }} user, if we created the user"
  when: 'create_k3s_user and node_k3s_role == "server"'
  become: true
  become_user: "{{ k3s_user }}"
  block:
    - name: "Make the {{ k3s_user }} user's .kube directory"
      ansible.builtin.file:
        path: '{{ k3s_user_home }}/.kube'
        state: directory
        owner: '{{ k3s_user | trim }}'
        group: '{{ k3s_group | trim }}'
        mode: '0750'

    - name: "Link /etc/rancher/k3s/k3s.yaml to the {{ k3s_user }} user's .kube/config"
      ansible.builtin.file:
        src: '/etc/rancher/k3s/k3s.yaml'
        path: '{{ k3s_user_home }}/.kube/config'
        state: link
        force: true
