argument_specs:
  main:
    short_description: "Initialization/setup role for K3s Ansible Galaxy collection"
    options:
      superuser_name:
        description: 'The name of the superuser.  If not specified, it will be determined automatically by executing a task with become=true and and become_user unspecified.'
        type: str
      k3s_hosts_group:
        description: |
          The inventory hosts group name for the nodes in the k3s cluster.
          This *MUST* match the inventory hosts group name used in the playbooks.
          Note that if you change this, the provided playbooks will fail, because their hosts attribute is set to match the
          default value for this fact.
          Changing this value requires writing your own playbooks, adapted from the provided playbooks, and matching their
          hosts attribute to the value of this fact.
          This is necessary because Ansible does not provide a way to get the unfiltered list of inventory hosts.
          The best it can muster is ansible_play_hosts_all, which provides the list of all hosts in the current play,
          but this may be filtered based on --limit (or -l) command-line argument.
          If the filtered list were to be used, it would throw off the calculations for which nodes are considered server
          nodes versus agent nodes.
          Because of this, the roles rely on the unfiltered inventory hosts list, which is why the k3s_hosts_group fact exists.
        type: str
      k3s_version:
        description: 'The version of k3s to install on the nodes'
        type: str
      k3s_cluster_pod_network_cidr:
        description: "The CIDR (subnet) for the k3s cluster's internal pod network"
        type: str
      k3s_enable_wireguard_network_encryption:
        description: 'Whether to enable wireguard encryption of network packets between nodes'
        type: bool
      k3s_storage_dir:
        description: |
          The directory where k3s will store its data.
          This is optional.  If not empty, this directory (typically a mounted filesystem)
          must exist on all nodes where k3s will be installed.  A symlink will be created
          when k3s is first installed on each node, from the default data directory to this
          directory.
        type: str
      create_k3s_user:
        description: |
          Whether to create a special user which can access the kubeconfig file and run kubectl commands on the cluster
        type: bool
      k3s_user:
        description: 'Username for the k3s user'
        type: str
      k3s_user_home:
        description: 'Home directory for the k3s user'
        type: str
      k3s_user_id:
        description: 'UID for the k3s user'
        type: int
      k3s_group:
        description: |
          Group name for the k3s group.
          The k3s group is always created on server nodes, because the group ownership of the kubeconfig file
          (/etc/rancher/k3s/k3s.yaml) is set to this group when k3s is installed in server mode on a node.
          This allows any user who is a member of the k3s group to access the kubeconfig file, in order to run kubectl
          commands on the cluster.
          The k3s group will only be created on server nodes.
        type: str
      k3s_group_id:
        description: 'GID for the k3s group'
        type: int
      num_k3s_server_nodes:
        description: |
          The number of k3s server nodes.
          All nodes beyond this number will be configured as agent nodes.
          This must be an odd number, and must be less than or equal to the number of hosts in the inventory hosts
          group specified in the k3s_hosts_group fact.
        type: int
      install_helm:
        description: |
          Whether to install Helm.  Note that Helm is required in order to install a lot of other packages,
          so if this is set to false, attempts to install any of the packages which require Helm will fail.
          Helm is only installed on server nodes.
        type: bool
      helm_version:
        description: 'The version of Helm to install'
        type: str
      install_headlamp:
        description: |
          Whether to install Headlamp.
          It is installed via Helm chart, so if install_headlamp is true
          and install_helm is false, the play will fail.
        type: bool
      headlamp_helm_chart_version:
        description: 'The Headlamp Helm chart version to install'
        type: str
      headlamp_helm_base_args:
        description: 'List of base arguments to pass to Helm when installing the Headlamp Helm chart'
        type: list
        elements: str
      headlamp_ingress_enabled:
        description: 'Whether to enable the Headlamp ingress'
        type: bool
      headlamp_ingress_path:
        description: 'Headlamp ingress URI path'
        type: path
      headlamp_ingress_path_type:
        description: 'Headlamp ingress path type'
        type: str
      headlamp_ingress_middlewares:
        description: 'List of Headlamp ingress middlwares to be annotated on the Headlamp ingress'
        type: list
        elements: str
      headlamp_ingress_extra_annotations:
        description: 'Dictionary of extra annotations for the Headlamp ingress'
        type: dict
      headlamp_ingress_annotations_combined:
        description: |
          Dictionary of annotations for the Headlamp ingress.
          By default, this is generated by combining annotations for headlamp_ingress_middlewares with
          any extra annotations specified in headlamp_ingress_extra_annotations.
          Normally, you would only override this value if you need to provide custom annotations which
          are not covered by the default combination of middlewares and extra annotations.
        type: dict
      headlamp_helm_ingress_args:
        description: |
          List of arguments to pass to Helm for configuring Headlamp ingress.
          By default, this is calculated based on the headlamp_ingress_* variables.
          Normally, you would only override this value if you need to provide a custom ingress configuration
          which is not covered by the default combination of options.
        type: list
        elements: str
      headlamp_helm_extra_args:
        description: 'List of extra arguments to pass to Helm when installing the Headlamp Helm chart'
        type: list
        elements: str
      install_longhorn:
        description: |
          Whether to install Longhorn block storage.
          It is installed via Helm chart, so if install_longhorn is true
          and install_helm is false, the play will fail.
        type: bool
      longhorn_helm_chart_version:
        description: 'The Longhorn Helm chart version to install'
        type: str
      longhorn_default_volume_replica_count:
        description: |
          The default number of replicas for Longhorn volumes.
          By default, this is automatically calculated based on the number of nodes in the cluster.
        type: int
      longhorn_helm_base_args:
        description: 'List of base arguments to pass to Helm when installing the Longhorn Helm chart'
        type: list
        elements: str
      longhorn_helm_storage_dir_args:
        description: |
          Arguments to pass to Helm for configuring the Longhorn storage directory when k3s_storage_dir is not empty.
          By default, this is calculated based on the k3s_storage_dir variable.
          Normally, you would only override this value if you need to provide a custom storage directory configuration
          for Longhorn volumes and metadata.
        type: list
        elements: str
      longhorn_ingress_enabled:
        description: 'Whether to enable the Longhorn ingress'
        type: bool
      longhorn_ingress_path:
        description: 'Longhorn ingress URI path'
        type: path
      longhorn_ingress_path_type:
        description: 'Longhorn ingress path type'
        type: str
      longhorn_ingress_middlewares:
        description: 'List of Longhorn ingress middlwares to be annotated on the Longhorn ingress'
        type: list
        elements: str
      longhorn_ingress_extra_annotations:
        description: 'Dictionary of extra annotations for the Longhorn ingress'
        type: dict
      longhorn_ingress_annotations_combined:
        description: |
          Dictionary of annotations for the Longhorn ingress.
          By default, this is generated by combining annotations for longhorn_ingress_middlewares with
          any extra annotations specified in longhorn_ingress_extra_annotations.
          Normally, you would only override this value if you need to provide custom annotations which
          are not covered by the default combination of middlewares and extra annotations.
        type: dict
      longhorn_helm_ingress_args:
        description: |
          List of arguments to pass to Helm for configuring Longhorn ingress.
          By default, this is calculated based on the longhorn_ingress_* variables.
          Normally, you would only override this value if you need to provide a custom ingress configuration
          which is not covered by the default combination of options.
        type: list
        elements: str
      longhorn_helm_extra_args:
        description: 'List of extra arguments to pass to Helm when installing the Longhorn Helm chart'
        type: list
        elements: str
      longhorn_ui_credentials:
        description: |
          List of usernames and passwords for accessing the Longhorn UI.
          Each element in the list must be a dictionary containing a 'username' and 'password' key, each with string values.
        type: list
        elements: dict
        no_log: true
      install_cni_plugins:
        description: 'Whether to install the CNI plugins on the nodes'
        type: bool
      cni_plugins_version:
        description: 'The version of the CNI plugins to install'
        type: str
      install_multus_cni:
        description: 'Whether to install multus-cni'
        type: bool
      multus_cni_version:
        description: 'The version of multus-cni to install'
        type: str
      multus_cni_protocol_version:
        description: 'The CNI protocol version for multus-cni'
        type: str
      install_whereabouts_ipam_plugin:
        description: |
          Whether to install whereabouts IPAM plugin.
          It is installed via Helm chart, so if install_whereabouts_ipam_plugin is true
          and install_helm is false, the play will fail.
        type: bool
      whereabouts_ipam_plugin_helm_chart_version:
        description: 'The version of whereabouts helm chart to install'
        type: str
      whereabouts_ipam_plugin_helm_extra_args:
        description: 'List of extra arguments to pass to Helm when installing the Whereabouts Helm chart'
        type: list
        elements: str
      install_emberstack_kubernetes_secrets_reflector:
        description: |
          Whether to install the Emberstack Kubernetes Secrets Reflector.
          It is installed via a Helm chart, so if install_emberstack_kubernetes_secrets_reflector is true
          and install_helm is false, the play will fail.
        type: bool
      emberstack_kubernetes_secrets_reflector_helm_chart_version:
        description: 'The version of the Emberstack Kubernetes Secrets Reflector helm chart to install'
        type: str
      emberstack_kubernetes_secrets_reflector_helm_extra_args:
        description: 'List of extra arguments to pass to Helm when installing the Emberstack Kubernetes Secrets Reflector Helm chart'
        type: list
        elements: str
      install_stakater_reloader:
        description: |
          Whether to install the Stakater Reloader.
          It is installed via a Helm chart, so if install_stakater_reloader is true
          and install_helm is false, the play will fail.
        type: bool
      stakater_reloader_helm_chart_version:
        description: 'The version of the Stakater Reloader helm chart to install'
        type: str
      stakater_reloader_helm_extra_args:
        description: 'List of extra arguments to pass to Helm when installing the Stakater Reloader Helm chart'
        type: list
        elements: str
      install_cert_manager:
        description: |
          Whether to install cert-manager.
          It is installed via a Helm chart, so if install_cert_manager is true
          and install_helm is false, the play will fail.
        type: bool
      cert_manager_helm_chart_version:
        description: 'The version of the cert-manager helm chart to install'
        type: str
      cert_manager_helm_extra_args:
        description: 'List of extra arguments to pass to Helm when installing the cert-manager Helm chart'
        type: list
        elements: str
      install_keepalived_cluster_load_balancer:
        description: 'Whether to install the Keepalived cluster load balancer'
        type: bool
      cluster_load_balancer_services:
        description: |
          List of services to be managed by the Keepalived cluster load balancer.
          Each service should be defined as a dictionary with the necessary configuration for the Keepalived cluster load balancer.
          Typical settings for HTTP and HTTPS services are as follows:
            - vrrp_instance_name: http_https
              network_interface: eth0
              virtual_router_id: 51
              ip_address: 1.2.3.4
              ports:
                - port_number: 80
                  health_check_protocol: http
                  health_check_path: /
                  health_check_healthy_status_codes: 200-299,404
                - port_number: 443
                  health_check_protocol: https
                  health_check_path: /
                  health_check_healthy_status_codes: 200-299,404
          Typical settings for TCP services are as follows (this example is for CloudNativePG [PostgreSQL] on port 5432):
            - vrrp_instance_name: cnpg1
              network_interface: enp65s0f2
              virtual_router_id: 53
              ip_address: 10.3.21.99
              ports:
                - port_number: 5432
                  health_check_protocol: tcp
        type: list
        elements: dict
