- name: "Run Whereabouts IPAM plugin installation tasks"
  run_once: true
  become: true
  become_user: "{{ k3s_user if create_k3s_user else superuser_name }}"
  block:
    - name: "Install or upgrade Whereabouts IPAM plugin via the Whereabouts Helm chart"
      ansible.builtin.include_role:
        name: helm_chart_install_or_upgrade
      vars:
        helm_namespace: "default"
        helm_release_name: "whereabouts"
        helm_repo_name: "whereabouts"
        helm_chart_name: "whereabouts-chart"
        helm_chart_url: "{{ whereabouts_ipam_plugin_helm_chart_url }}"
        helm_chart_version: "{{ whereabouts_ipam_plugin_helm_chart_version }}"
        helm_args: "{{ whereabouts_ipam_plugin_helm_extra_args }}"
