- name: "Set up a K3s cluster"
  hosts: all_hosts

  roles:
    - name: init
      tags: [always]
    - name: prereq
      tags: [k3s, prereq]
    - name: k3s_cluster
      tags: [k3s, k3s_cluster]
    - name: helm
      tags: [helm]
    - name: cni_plugins
      tags: [cni_plugins]
    - name: multus_cni
      tags: [multus_cni]
    # TODO: Add role for installing longhorn
    - name: headlamp
      tags: [headlamp]
    - name: headlamp_token
      tags: [headlamp, headlamp_token]
