- name: "Set up a K3s cluster"
  hosts: all_hosts

  roles:
    - name: init
      tags: [always]
    - name: prereq
      tags: [k3s, prereq]
    - name: k3s_cluster
      tags: [k3s, k3s_cluster]
    - name: helm
      tags: [helm]
    - name: headlamp
      tags: [headlamp]
    - name: headlamp_token
      tags: [headlamp, headlamp_token]
    # TODO: Add role for installing CNI plugins
    # TODO: Add role for installing multus-cni
    # TODO: Add role for installing longhorn
