- name: "Set up a K3s cluster"
  hosts: all_hosts

  roles:
    - role: init
      tags: [always]
    - role: prereq
      tags: [k3s, prereq]
    - role: k3s_cluster
      tags: [k3s, k3s_cluster]
    - role: helm
      tags: [helm]
      when: install_helm
    - role: whereabouts
      tags: [whereabouts]
      when: install_whereabouts_ipam_plugin
    - role: cni_plugins
      tags: [cni_plugins]
      when: install_cni_plugins
    - role: multus_cni
      tags: [multus_cni]
      when: install_multus_cni
    - role: longhorn
      tags: [longhorn]
      when: install_longhorn
    - role: headlamp
      tags: [headlamp, install_headlamp]
      when: install_headlamp
    - role: headlamp_token
      tags: [headlamp, headlamp_token]
      when: install_headlamp
