- name: "Run Cert-Manager installation tasks"
  run_once: true
  become: true
  become_user: "{{ k3s_user if create_k3s_user else superuser_name }}"
  block:
    - name: "Install or upgrade Cert-Manager via the Cert-Manager Helm chart"
      ansible.builtin.include_role:
        name: helm_chart_install_or_upgrade
      vars:
        helm_namespace: "cert-manager"
        helm_release_name: "cert-manager"
        helm_repo_name: ""
        helm_chart_name: "cert-manager"
        helm_chart_url: "{{ cert_manager_helm_chart_url }}"
        helm_chart_version: "{{ cert_manager_helm_chart_version }}"
        helm_args: "{{ cert_manager_helm_base_args + cert_manager_helm_extra_args }}"
        helm_diff_yq_filter_expressions:
          - 'select((.kind == "Job" and .metadata.name == "cert-manager-startupapicheck") | not)'
          - 'select((.kind == "Role" and .metadata.name == "cert-manager-startupapicheck:create-cert") | not)'
          - 'select((.kind == "RoleBinding" and .metadata.name == "cert-manager-startupapicheck:create-cert") | not)'
          - 'select((.kind == "ServiceAccount" and .metadata.name == "cert-manager-startupapicheck") | not)'
