# This cluster uses sudo.ws.  Without the next line, all tasks with "become: true" will fail.
ansible_become_exe: /usr/bin/sudo.ws

k3s_storage_dir: "/storage"
install_cni_plugins: true
install_multus_cni: true
