# This cluster uses sudo.ws.  Without the next line, all tasks with "become: true" will fail.
ansible_become_exe: /usr/bin/sudo.ws

k3s_storage_dir: "/storage"
install_cni_plugins: true
install_multus_cni: true

longhorn_ingress_enabled: true
longhorn_ui_credentials:
  - username: "lhadmin"
    password: "adMiNlH3223"

# install_keepalived_cluster_load_balancer: true
# cluster_load_balancer_services:
#   - vrrp_instance_name: http_https
#     network_interface: enp0s1
#     virtual_router_id: 51
#     ip_address: 1.2.3.4
#     ports:
#       - port_number: 80
#         health_check_protocol: http
#         health_check_path: /
#         health_check_healthy_status_codes: 200-299,404
#       - port_number: 443
#         health_check_protocol: https
#         health_check_path: /
#         health_check_healthy_status_codes: 200-299,404
#   - vrrp_instance_name: cnpg1
#     network_interface: eth0
#     virtual_router_id: 53
#     ip_address: 1.2.3.5
#     ports:
#       - port_number: 5432
#         health_check_protocol: tcp
