- name: "Assert that num_k3s_server_nodes is odd, and less than or equal to the number of k3s nodes"
  run_once: true
  ansible.builtin.assert:
    that: 'num_k3s_server_nodes is odd and num_k3s_server_nodes > 0 and num_k3s_server_nodes <= (groups[k3s_hosts_group] | length)'

- name: "Assert that install_cni_plugins is true if any of the optional components which require CNI plugins are enabled"
  when: 'install_multus_cni'
  run_once: true
  ansible.builtin.assert:
    that: install_cni_plugins

- name: "Assert that install_helm is true if any of the optional components which require Helm are enabled"
  when: 'install_headlamp or install_longhorn'
  run_once: true
  ansible.builtin.assert:
    that: install_helm

- name: "Get the username, group name, and home directory of the superuser"
  become: true
  ansible.builtin.shell:
    cmd: |
      set -euo pipefail

      id -un
      id -gn
      echo $HOME
  args:
    executable: /bin/bash
  register: init_result_superuser_info

- name: "Set superuser information as facts"
  ansible.builtin.set_fact:
    superuser_name: '{{ init_result_superuser_info.stdout_lines[0] | trim }}'
    superuser_group: '{{ init_result_superuser_info.stdout_lines[1] | trim }}'
    superuser_home: '{{ init_result_superuser_info.stdout_lines[2] | trim }}'
